[workspace]
members = [
  "cli",
  "crates/ingestion",
  "crates/processing",
  "crates/storage",
  "crates/types",
  "crates/utils",
  "crates/tui",
  "crates/config",
  "proto-build",
]

resolver = "2"

[workspace.dependencies]
tonic = "0.14.3"
prost = "0.14.3"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.13", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
config = "0.15.19"
dotenv = "0.15.0"
tonic-prost-build = "0.14.3"
