[workspace]
members = [
  "cli",
  "crates/ingestor",
  "crates/engine",
  "crates/storage",
  "crates/types",
  "crates/utils",
  "crates/tui",
  "crates/settings",
  "proto-build",
]

resolver = "2"

[workspace.dependencies]
prost = "0.14.3"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "fs"] }
reqwest = { version = "0.13", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
config = "0.15.19"
dotenv = "0.15.0"
tonic-prost-build = "0.14.3"
tonic-prost = "0.14.3"
prost-types = "0.14.3"
tonic = { version = "0.14.3", features = [
  "tls-webpki-roots",
  "channel",
  "gzip",
] }
hex = "0.4.3"
async-stream = "0.3.6"
futures-util = "0.3.31"
