[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
settings = { path = "../crates/settings/" }
engine = { path = "../crates/engine/" }
ingestor = { path = "../crates/ingestor/" }
dotenv.workspace = true
config.workspace = true
tokio.workspace = true
futures-util.workspace = true
clickhouse.workspace = true
anyhow.workspace = true

[build-dependencies]
