[package]
name = "ingestion"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic.workspace = true
prost.workspace = true
serde.workspace = true
reqwest.workspace = true
hex.workspace = true
proto-build = { path = "../../proto-build" }
settings = { path = "../settings/" }
async-stream.workspace = true
futures-util.workspace = true

[build-dependencies]
