auth_endpoint = "https://auth.streamingfast.io/v1/auth/issue"
endpoint_url = "https://mainnet.eth.streamingfast.io:443"
start_block = 24_000_001
end_block = 24_000_001
final_blocks_only = true


[block]
hash = true
number = true
size = true
detail_level = true
ver = true


[block.blockheader]
enabled = false

parent_hash = false
uncle_hash = false
coinbase = false
state_root = false
transactions_root = false
receipt_root = false
logs_bloom = false
difficulty = false
total_difficulty = false
number = false
gas_limit = false
gas_used = false
timestamp = false
extra_data = false
mix_hash = false
nonce = false
hash = false
base_fee_per_gas = false
withdrawals_root = false
tx_dependency = false
blob_gas_used = false
excess_blob_gas = false
parent_beacon_root = false
requests_hash = false


[block.system_calls]
enabled = false

index = false
parent_index = false
depth = false
call_type = false
caller = false
address = false
address_delegates_to = false
value = false
gas_limit = false
gas_consumed = false
return_data = false
input = false
executed_code = false
suicide = false
keccak_preimages = false
status_failed = false
status_reverted = false
failure_reason = false
state_reverted = false
begin_ordinal = false
end_ordinal = false


[block.system_calls.storage_changes]
enabled = false

address = false
key = false
old_value = false
new_value = false
ordinal = false

[block.system_calls.balance_changes]
enabled = false

address = false
old_value = false
new_value = false
reason = false
ordinal = false

[block.system_calls.nonce_changes]
enabled = false

address = false
old_value = false
new_value = false
ordinal = false


[block.system_calls.code_changes]
address = false
old_hash = false
old_code = false
new_hash = false
new_code = false
ordinal = false

[block.system_calls.gas_changes]
enabled = false

old_value = false
new_value = false
reason = false
ordinal = false

[block.system_calls.account_creations]
enabled = false

account = false
ordinal = false


[block.uncles]
enabled = false

parent_hash = false
uncle_hash = false
coinbase = false
state_root = false
transactions_root = false
receipt_root = false
logs_bloom = false
difficulty = false
total_difficulty = false
number = false
gas_limit = false
gas_used = false
timestamp = false
extra_data = false
mix_hash = false
nonce = false
hash = false
base_fee_per_gas = false
withdrawals_root = false
tx_dependency = false
blob_gas_used = false
excess_blob_gas = false
parent_beacon_root = false
requests_hash = false


[block.transaction_traces]
enabled = false
to = false
nonce = false
gas_price = false
gas_limit = false
value = false
input = false
v = false
r = false
s = false
gas_used = false
type = false
max_fee_per_gas = false
max_priority_fee_per_gas = false
index = false
hash = false
from = false
return_data = false
public_key = false
begin_ordinal = false
end_ordinal = false
status = false
blob_gas = false
blob_gas_fee_cap = false
blob_hashes = false

[block.transaction_traces.set_code_authorizations]
enabled = false
discarded = false
chain_id = false
address = false
nonce = false
v = false
r = false
s = false
authority = false

[block.transaction_traces.receipt]
enabled = false
state_root = false
cumulative_gas_used = false
logs_bloom = false
blob_gas_used = false
blob_gas_price = false

[block.transaction_traces.receipt.logs]
enabled = false
address = false
topics = false
data = false
index = false
block_index = false
ordinal = false


[block.transaction_traces.calls]
enabled = false
index = false
parent_index = false
depth = false
call_type = false
caller = false
address = false
address_delegates_to = false
value = false
gas_limit = false
gas_consumed = false
return_data = false
input = false
executed_code = false
suicide = false
keccak_preimages = false
status_failed = false
status_reverted = false
failure_reason = false
state_reverted = false
begin_ordinal = false
end_ordinal = false

[block.transaction_traces.calls.storage_changes]
enabled = false
address = false
key = false
old_value = false
new_value = false
ordinal = false

[block.transaction_traces.calls.balance_changes]
enabled = false
address = false
old_value = false
new_value = false
reason = false
ordinal = false

[block.transaction_traces.calls.nonce_changes]
enabled = false
address = false
old_value = false
new_value = false
ordinal = false

[block.transaction_traces.calls.gas_changes]
enabled = false
old_value = false
new_value = false
reason = false
ordinal = false

[block.transaction_traces.access_list]
enabled = false

address = false
storage_keys = false


[block.transaction_traces.calls.code_changes]
enabled = false
address = false
old_hash = false
old_code = false
new_hash = false
new_code = false
ordinal = false


[block.transaction_traces.calls.account_creations]
enabled = false

account = false
ordinal = false

[block.balance_changes]
enabled = false
address = false
old_value = false
new_value = false
reason = false
ordinal = false

[block.code_changes]
enabled = false
address = false
old_hash = false
old_code = false
new_hash = false
new_code = false
ordinal = false

[block.withdrawals]
enabled = false
index = false
validator_index = false
address = false
amount = false
